// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeVYCc0dN2QzKtUjfNCZIWgkcZ_hjLVJY',
    appId: '1:772888735384:web:352fd584025ebdd7a36aed',
    messagingSenderId: '772888735384',
    projectId: 'insight-66ca7',
    authDomain: 'insight-66ca7.firebaseapp.com',
    storageBucket: 'insight-66ca7.appspot.com',
    measurementId: 'G-S9GE8JMFEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJdZCotrhj-UvGx5nQE1Hjs1eSa-AZlPs',
    appId: '1:772888735384:android:0061113416c77350a36aed',
    messagingSenderId: '772888735384',
    projectId: 'insight-66ca7',
    storageBucket: 'insight-66ca7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnGT8Tf0nPVbLwyhHBK32hmtDnbqTMheY',
    appId: '1:772888735384:ios:c85024e1130b5e32a36aed',
    messagingSenderId: '772888735384',
    projectId: 'insight-66ca7',
    storageBucket: 'insight-66ca7.appspot.com',
    iosBundleId: 'com.example.insighted2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnGT8Tf0nPVbLwyhHBK32hmtDnbqTMheY',
    appId: '1:772888735384:ios:c85024e1130b5e32a36aed',
    messagingSenderId: '772888735384',
    projectId: 'insight-66ca7',
    storageBucket: 'insight-66ca7.appspot.com',
    iosBundleId: 'com.example.insighted2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeVYCc0dN2QzKtUjfNCZIWgkcZ_hjLVJY',
    appId: '1:772888735384:web:b0bd2c6750d64952a36aed',
    messagingSenderId: '772888735384',
    projectId: 'insight-66ca7',
    authDomain: 'insight-66ca7.firebaseapp.com',
    storageBucket: 'insight-66ca7.appspot.com',
    measurementId: 'G-7NQL57MJ5B',
  );

}